title: Victor Barbarosh Portfolio
description: This site unifies my writings across various platforms - Baeldung, Substack, and Medium.
show_downloads: false
show_platforms: true
google_analytics: GTM-MSPCKDWK
theme: jekyll-theme-architect
github:
  zip_url: http://example.com/download.zip
  another_url: another value
platforms:
  baeldung: https://www.baeldung.com/editor/victorbarbarosh
  substack: https://substack.com/@theanatomyofanalgorithm
  medium: https://medium.com/@geeks.sw.gig

#  On Medium, I write haikus and explore topics in Full Stack Development and AI.
#  As a Baeldung contributor, I focus on Java Core and Spring Framework.
#  On Substack, I delve into Data Structures, Algorithms, and other topics from my full stack development work.
#
#  Explore to find a mix of technical insights and creative writing!